//! openparts-librepcb: LibrePCB adapter behind the openparts-pcbcad IR
//! (Architecture Specification section 12/13). Unlike KiCad's single
//! `.kicad_sym`/`.kicad_mod` files, a usable LibrePCB library element
//! requires four linked element types -- Symbol, Package, Component,
//! and Device -- each its own UUID-named directory inside a `.lplib`
//! library directory. `generate_library` produces the full file set for
//! one part in one call.
//!
//! Format reverse-engineered from real files in LibrePCB's own official
//! base library (github.com/LibrePCB-Libraries/LibrePCB_Base.lplib) and
//! the authoritative `SignalRole` enum in LibrePCB's own source
//! (libs/librepcb/core/types/signalrole.h) -- not guessed from memory,
//! per this project's research discipline. Not independently verified
//! against a real LibrePCB install (none available in this
//! environment); a stretch goal for whoever picks this up next.

mod uuid_gen;

use openparts_pcbcad::{GraphicKind, PcbFootprint, PcbSymbol, PinElectricalType, PinOrientation};
use uuid::Uuid;

/// One file to write, with a path relative to the library's root
/// directory (e.g. `sym/<uuid>/symbol.lp`).
#[derive(Debug, Clone, PartialEq)]
pub struct LpFile {
    pub path: String,
    pub content: String,
}

/// Fixed generation timestamp (not a real creation date -- a stable
/// placeholder so output is byte-reproducible, same policy as
/// openparts-step's FILE_NAME timestamp).
const GENERATED_TIMESTAMP: &str = "2026-01-01T00:00:00Z";

fn pin_role(t: PinElectricalType) -> &'static str {
    match t {
        PinElectricalType::Input => "input",
        PinElectricalType::Output => "output",
        PinElectricalType::Bidirectional => "inout",
        PinElectricalType::PowerIn => "power",
        PinElectricalType::Passive => "passive",
        // LibrePCB's SignalRole has no "no connect"/"unspecified" role
        // (only passive/power/input/output/inout/opendrain) -- "passive"
        // is the closest neutral fit for a pin that carries no defined
        // electrical direction, matching common EDA-tool convention for
        // reserved/NC pins. Not a verbatim spec mapping.
        PinElectricalType::NoConnect | PinElectricalType::Unspecified => "passive",
    }
}

fn pin_rotation(o: PinOrientation) -> f64 {
    // Same angle convention as openparts-kicad's orientation_angle:
    // rotation is the direction the pin's free end points away from its
    // base position.
    match o {
        PinOrientation::Left => 0.0,
        PinOrientation::Bottom => 90.0,
        PinOrientation::Right => 180.0,
        PinOrientation::Top => 270.0,
    }
}

fn fmt_uuid(u: Uuid) -> String {
    u.to_string()
}

fn render_symbol(mpn: &str, symbol: &PcbSymbol, sym_uuid: Uuid, cmpcat_uuid: Uuid) -> String {
    let mut out = String::new();
    out.push_str(&format!("(librepcb_symbol {}\n", fmt_uuid(sym_uuid)));
    out.push_str(&format!(" (name \"{mpn}\")\n"));
    out.push_str(" (description \"Generated by OpenParts from Canonical Data.\")\n");
    out.push_str(" (keywords \"\")\n");
    out.push_str(" (author \"OpenParts\")\n");
    out.push_str(" (version \"0.1\")\n");
    out.push_str(&format!(" (created {GENERATED_TIMESTAMP})\n"));
    out.push_str(" (deprecated false)\n");
    out.push_str(" (generated_by \"\")\n");
    out.push_str(&format!(" (category {})\n", fmt_uuid(cmpcat_uuid)));
    out.push_str(" (grid_interval 2.54)\n");

    for pin in &symbol.pins {
        let pin_uuid = uuid_gen::derive(&format!("sym-pin:{mpn}:{}", pin.number));
        out.push_str(&format!(
            " (pin {} (name \"{}\")\n",
            fmt_uuid(pin_uuid),
            pin.name
        ));
        out.push_str(&format!(
            "  (position {:.2} {:.2}) (rotation {:.1}) (length {:.2})\n",
            pin.position.x,
            pin.position.y,
            pin_rotation(pin.orientation),
            pin.length
        ));
        out.push_str("  (name_position 2.5 0.0) (name_rotation 0.0) (name_height 2.0)\n");
        out.push_str("  (name_align left bottom)\n");
        out.push_str(" )\n");
    }

    for (i, graphic) in symbol.graphics.iter().enumerate() {
        let GraphicKind::Rectangle { start, end } = graphic.kind;
        let poly_uuid = uuid_gen::derive(&format!("sym-outline:{mpn}:{i}"));
        out.push_str(&format!(
            " (polygon {} (layer sym_outlines)\n",
            fmt_uuid(poly_uuid)
        ));
        out.push_str("  (width 0.2) (fill false) (grab_area true)\n");
        out.push_str(&format!(
            "  (vertex (position {:.2} {:.2}) (angle 0.0))\n",
            start.x, start.y
        ));
        out.push_str(&format!(
            "  (vertex (position {:.2} {:.2}) (angle 0.0))\n",
            end.x, start.y
        ));
        out.push_str(&format!(
            "  (vertex (position {:.2} {:.2}) (angle 0.0))\n",
            end.x, end.y
        ));
        out.push_str(&format!(
            "  (vertex (position {:.2} {:.2}) (angle 0.0))\n",
            start.x, end.y
        ));
        out.push_str(&format!(
            "  (vertex (position {:.2} {:.2}) (angle 0.0))\n",
            start.x, start.y
        ));
        out.push_str(" )\n");

        let name_text_uuid = uuid_gen::derive(&format!("sym-name-text:{mpn}"));
        let value_text_uuid = uuid_gen::derive(&format!("sym-value-text:{mpn}"));
        out.push_str(&format!(
            " (text {} (layer sym_names) (height 2.5)\n",
            fmt_uuid(name_text_uuid)
        ));
        out.push_str(&format!(
            "  (align left bottom) (position {:.2} {:.2}) (rotation 0.0) (lock false)\n",
            start.x, end.y
        ));
        out.push_str("  (value \"{{NAME}}\")\n )\n");
        out.push_str(&format!(
            " (text {} (layer sym_values) (height 2.5)\n",
            fmt_uuid(value_text_uuid)
        ));
        out.push_str(&format!(
            "  (align left top) (position {:.2} {:.2}) (rotation 0.0) (lock false)\n",
            start.x, start.y
        ));
        out.push_str("  (value \"{{VALUE}}\")\n )\n");
    }

    out.push(')');
    out.push('\n');
    out
}

fn render_package(
    mpn: &str,
    footprint: &PcbFootprint,
    pkg_uuid: Uuid,
    fp_uuid: Uuid,
    pkgcat_uuid: Uuid,
) -> String {
    let mut out = String::new();
    out.push_str(&format!("(librepcb_package {}\n", fmt_uuid(pkg_uuid)));
    out.push_str(&format!(" (name \"{mpn}\")\n"));
    out.push_str(" (description \"Generated by OpenParts from Mechanical Geometry.\")\n");
    out.push_str(" (keywords \"\")\n");
    out.push_str(" (author \"OpenParts\")\n");
    out.push_str(" (version \"0.1\")\n");
    out.push_str(&format!(" (created {GENERATED_TIMESTAMP})\n"));
    out.push_str(" (deprecated false)\n");
    out.push_str(" (generated_by \"\")\n");
    out.push_str(&format!(" (category {})\n", fmt_uuid(pkgcat_uuid)));
    out.push_str(" (assembly_type smt)\n");
    out.push_str(" (grid_interval 2.54)\n");
    out.push_str(" (min_copper_clearance 0.15)\n");

    for pad in &footprint.pads {
        let pad_uuid = uuid_gen::derive(&format!("pkg-pad:{mpn}:{}", pad.number));
        out.push_str(&format!(
            " (pad {} (name \"{}\"))\n",
            fmt_uuid(pad_uuid),
            pad.number
        ));
    }

    out.push_str(&format!(" (footprint {}\n", fmt_uuid(fp_uuid)));
    out.push_str("  (name \"default\")\n");
    out.push_str("  (description \"\")\n");
    out.push_str("  (3d_position 0.0 0.0 0.0) (3d_rotation 0.0 0.0 0.0)\n");
    for pad in &footprint.pads {
        let pad_uuid = uuid_gen::derive(&format!("pkg-pad:{mpn}:{}", pad.number));
        out.push_str(&format!(
            "  (pad {} (side top) (shape roundrect)\n",
            fmt_uuid(pad_uuid)
        ));
        out.push_str(&format!(
            "   (position {:.3} {:.3}) (rotation 0.0) (size {:.3} {:.3}) (radius 0.0)\n",
            pad.position.x, pad.position.y, pad.size.0, pad.size.1
        ));
        out.push_str(
            "   (stop_mask auto) (solder_paste auto) (clearance 0.0) (function standard)\n",
        );
        out.push_str(&format!("   (package_pad {})\n", fmt_uuid(pad_uuid)));
        out.push_str("  )\n");
    }
    out.push_str(" )\n)\n");
    out
}

fn render_component(
    mpn: &str,
    symbol: &PcbSymbol,
    cmp_uuid: Uuid,
    sym_uuid: Uuid,
    cmpcat_uuid: Uuid,
) -> String {
    let variant_uuid = uuid_gen::derive(&format!("cmp-variant:{mpn}"));
    let gate_uuid = uuid_gen::derive(&format!("cmp-gate:{mpn}"));

    let mut out = String::new();
    out.push_str(&format!("(librepcb_component {}\n", fmt_uuid(cmp_uuid)));
    out.push_str(&format!(" (name \"{mpn}\")\n"));
    out.push_str(" (description \"Generated by OpenParts from Canonical Data.\")\n");
    out.push_str(" (keywords \"\")\n");
    out.push_str(" (author \"OpenParts\")\n");
    out.push_str(" (version \"0.1\")\n");
    out.push_str(&format!(" (created {GENERATED_TIMESTAMP})\n"));
    out.push_str(" (deprecated false)\n");
    out.push_str(" (generated_by \"\")\n");
    out.push_str(&format!(" (category {})\n", fmt_uuid(cmpcat_uuid)));
    out.push_str(" (schematic_only false)\n");
    out.push_str(" (default_value \"\")\n");
    // "U" is a generator default (no reference-designator-prefix concept
    // exists in openparts-core yet), not a canonical fact.
    out.push_str(" (prefix \"U\")\n");

    for pin in &symbol.pins {
        let signal_uuid = uuid_gen::derive(&format!("cmp-signal:{mpn}:{}", pin.number));
        out.push_str(&format!(
            " (signal {} (name \"{}\") (role {})\n",
            fmt_uuid(signal_uuid),
            pin.name,
            pin_role(pin.electrical_type)
        ));
        out.push_str("  (required false) (negated false) (clock false) (forced_net \"\")\n )\n");
    }

    out.push_str(&format!(
        " (variant {} (norm \"\")\n",
        fmt_uuid(variant_uuid)
    ));
    out.push_str("  (name \"default\")\n");
    out.push_str("  (description \"\")\n");
    out.push_str(&format!("  (gate {}\n", fmt_uuid(gate_uuid)));
    out.push_str(&format!("   (symbol {})\n", fmt_uuid(sym_uuid)));
    out.push_str("   (position 0.0 0.0) (rotation 0.0) (required true) (suffix \"\")\n");
    for pin in &symbol.pins {
        let pin_uuid = uuid_gen::derive(&format!("sym-pin:{mpn}:{}", pin.number));
        let signal_uuid = uuid_gen::derive(&format!("cmp-signal:{mpn}:{}", pin.number));
        out.push_str(&format!(
            "   (pin {} (signal {}) (text signal))\n",
            fmt_uuid(pin_uuid),
            fmt_uuid(signal_uuid)
        ));
    }
    out.push_str("  )\n");
    out.push_str(" )\n)\n");
    out
}

fn render_device(
    mpn: &str,
    footprint: &PcbFootprint,
    dev_uuid: Uuid,
    cmp_uuid: Uuid,
    pkg_uuid: Uuid,
    cmpcat_uuid: Uuid,
) -> String {
    let mut out = String::new();
    out.push_str(&format!("(librepcb_device {}\n", fmt_uuid(dev_uuid)));
    out.push_str(&format!(" (name \"{mpn}\")\n"));
    out.push_str(" (description \"Generated by OpenParts from Canonical Data.\")\n");
    out.push_str(" (keywords \"\")\n");
    out.push_str(" (author \"OpenParts\")\n");
    out.push_str(" (version \"0.1\")\n");
    out.push_str(&format!(" (created {GENERATED_TIMESTAMP})\n"));
    out.push_str(" (deprecated false)\n");
    out.push_str(" (generated_by \"\")\n");
    out.push_str(&format!(" (category {})\n", fmt_uuid(cmpcat_uuid)));
    out.push_str(&format!(" (component {})\n", fmt_uuid(cmp_uuid)));
    out.push_str(&format!(" (package {})\n", fmt_uuid(pkg_uuid)));
    for pad in &footprint.pads {
        let pad_uuid = uuid_gen::derive(&format!("pkg-pad:{mpn}:{}", pad.number));
        let signal_uuid = uuid_gen::derive(&format!("cmp-signal:{mpn}:{}", pad.number));
        out.push_str(&format!(
            " (pad {} (optional false)\n  (signal {})\n )\n",
            fmt_uuid(pad_uuid),
            fmt_uuid(signal_uuid)
        ));
    }
    out.push(')');
    out.push('\n');
    out
}

fn render_category(kind: &str, uuid: Uuid) -> String {
    format!(
        "(librepcb_{kind}_category {}\n (name \"OpenParts Generated\")\n (description \"\")\n (keywords \"\")\n (author \"OpenParts\")\n (version \"0.1\")\n (created {GENERATED_TIMESTAMP})\n (deprecated false)\n)\n",
        fmt_uuid(uuid)
    )
}

fn render_library(lib_uuid: Uuid) -> String {
    format!(
        "(librepcb_library {}\n (name \"OpenParts Generated\")\n (description \"Generated by OpenParts from Canonical Data. See https://github.com/openparts-org/openparts\")\n (keywords \"\")\n (author \"OpenParts\")\n (version \"0.1\")\n (created {GENERATED_TIMESTAMP})\n (deprecated false)\n (url \"\")\n (manufacturer \"\")\n)\n",
        fmt_uuid(lib_uuid)
    )
}

/// Generates a complete, self-contained `.lplib` library directory
/// (Symbol + Package + Component + Device, plus one shared package/
/// component category and the library manifest) for one part. Every
/// UUID is derived deterministically from `mpn`, so calling this again
/// for the same input always reproduces byte-identical files, and
/// calling it for a different `mpn` never collides with a previous
/// part's files -- both outputs can be merged into the same `.lplib`
/// directory on disk.
pub fn generate_library(mpn: &str, symbol: &PcbSymbol, footprint: &PcbFootprint) -> Vec<LpFile> {
    let lib_uuid = uuid_gen::derive("library");
    let pkgcat_uuid = uuid_gen::derive("pkgcat:openparts-generated");
    let cmpcat_uuid = uuid_gen::derive("cmpcat:openparts-generated");
    let sym_uuid = uuid_gen::derive(&format!("sym:{mpn}"));
    let pkg_uuid = uuid_gen::derive(&format!("pkg:{mpn}"));
    let fp_uuid = uuid_gen::derive(&format!("footprint:{mpn}"));
    let cmp_uuid = uuid_gen::derive(&format!("cmp:{mpn}"));
    let dev_uuid = uuid_gen::derive(&format!("dev:{mpn}"));

    vec![
        LpFile {
            path: ".librepcb-lib".to_string(),
            content: "2\n".to_string(),
        },
        LpFile {
            path: "library.lp".to_string(),
            content: render_library(lib_uuid),
        },
        LpFile {
            path: format!("pkgcat/{}/.librepcb-pkgcat", fmt_uuid(pkgcat_uuid)),
            content: "2\n".to_string(),
        },
        LpFile {
            path: format!("pkgcat/{}/package_category.lp", fmt_uuid(pkgcat_uuid)),
            content: render_category("package", pkgcat_uuid),
        },
        LpFile {
            path: format!("cmpcat/{}/.librepcb-cmpcat", fmt_uuid(cmpcat_uuid)),
            content: "2\n".to_string(),
        },
        LpFile {
            path: format!("cmpcat/{}/component_category.lp", fmt_uuid(cmpcat_uuid)),
            content: render_category("component", cmpcat_uuid),
        },
        LpFile {
            path: format!("sym/{}/.librepcb-sym", fmt_uuid(sym_uuid)),
            content: "2\n".to_string(),
        },
        LpFile {
            path: format!("sym/{}/symbol.lp", fmt_uuid(sym_uuid)),
            content: render_symbol(mpn, symbol, sym_uuid, cmpcat_uuid),
        },
        LpFile {
            path: format!("pkg/{}/.librepcb-pkg", fmt_uuid(pkg_uuid)),
            content: "2\n".to_string(),
        },
        LpFile {
            path: format!("pkg/{}/package.lp", fmt_uuid(pkg_uuid)),
            content: render_package(mpn, footprint, pkg_uuid, fp_uuid, pkgcat_uuid),
        },
        LpFile {
            path: format!("cmp/{}/.librepcb-cmp", fmt_uuid(cmp_uuid)),
            content: "2\n".to_string(),
        },
        LpFile {
            path: format!("cmp/{}/component.lp", fmt_uuid(cmp_uuid)),
            content: render_component(mpn, symbol, cmp_uuid, sym_uuid, cmpcat_uuid),
        },
        LpFile {
            path: format!("dev/{}/.librepcb-dev", fmt_uuid(dev_uuid)),
            content: "2\n".to_string(),
        },
        LpFile {
            path: format!("dev/{}/device.lp", fmt_uuid(dev_uuid)),
            content: render_device(mpn, footprint, dev_uuid, cmp_uuid, pkg_uuid, cmpcat_uuid),
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;
    use openparts_pcbcad::{Graphic, GraphicKind, Pad, PadShape, Point2, SymbolPin, SymbolUnit};

    fn synthetic_symbol() -> PcbSymbol {
        PcbSymbol {
            name: "TEST".into(),
            units: vec![SymbolUnit { index: 1 }],
            pins: vec![
                SymbolPin {
                    number: "1".into(),
                    name: "VDD".into(),
                    electrical_type: PinElectricalType::PowerIn,
                    position: Point2 { x: -7.62, y: 0.0 },
                    length: 2.54,
                    orientation: PinOrientation::Left,
                    unit: 1,
                    hidden: false,
                },
                SymbolPin {
                    number: "2".into(),
                    name: "GPIO0".into(),
                    electrical_type: PinElectricalType::Bidirectional,
                    position: Point2 { x: 7.62, y: 0.0 },
                    length: 2.54,
                    orientation: PinOrientation::Right,
                    unit: 1,
                    hidden: false,
                },
            ],
            graphics: vec![Graphic {
                kind: GraphicKind::Rectangle {
                    start: Point2 { x: -5.08, y: 5.08 },
                    end: Point2 { x: 5.08, y: -5.08 },
                },
            }],
        }
    }

    fn synthetic_footprint() -> PcbFootprint {
        PcbFootprint {
            name: "TEST".into(),
            pads: vec![
                Pad {
                    number: "1".into(),
                    position: Point2 { x: -1.0, y: 0.0 },
                    size: (0.4, 0.25),
                    shape: PadShape::Rect,
                },
                Pad {
                    number: "2".into(),
                    position: Point2 { x: 1.0, y: 0.0 },
                    size: (0.4, 0.25),
                    shape: PadShape::Rect,
                },
            ],
            graphics: vec![],
            courtyard: None,
        }
    }

    #[test]
    fn produces_one_file_per_element_plus_categories_and_manifest() {
        let files = generate_library("TESTPART", &synthetic_symbol(), &synthetic_footprint());
        // .librepcb-lib + library.lp + 2*(cat id+cat) + 2*(sym id+sym)
        // + 2*(pkg id+pkg) + 2*(cmp id+cmp) + 2*(dev id+dev) = 14
        assert_eq!(files.len(), 14);
        assert!(files.iter().any(|f| f.path == "library.lp"));
        assert!(files.iter().any(|f| f.path.ends_with("symbol.lp")));
        assert!(files.iter().any(|f| f.path.ends_with("package.lp")));
        assert!(files.iter().any(|f| f.path.ends_with("component.lp")));
        assert!(files.iter().any(|f| f.path.ends_with("device.lp")));
    }

    #[test]
    fn symbol_has_two_pins() {
        let files = generate_library("TESTPART", &synthetic_symbol(), &synthetic_footprint());
        let symbol_lp = &files
            .iter()
            .find(|f| f.path.ends_with("symbol.lp"))
            .unwrap()
            .content;
        assert_eq!(symbol_lp.matches("(pin ").count(), 2);
    }

    #[test]
    fn package_has_two_pads_and_one_footprint() {
        let files = generate_library("TESTPART", &synthetic_symbol(), &synthetic_footprint());
        let package_lp = &files
            .iter()
            .find(|f| f.path.ends_with("package.lp"))
            .unwrap()
            .content;
        // 2 abstract pads + 2 footprint pads = 4 "(pad " occurrences.
        assert_eq!(package_lp.matches("(pad ").count(), 4);
        assert_eq!(package_lp.matches("(footprint ").count(), 1);
    }

    #[test]
    fn generation_is_deterministic_across_runs() {
        let a = generate_library("TESTPART", &synthetic_symbol(), &synthetic_footprint());
        let b = generate_library("TESTPART", &synthetic_symbol(), &synthetic_footprint());
        assert_eq!(a, b);
    }

    #[test]
    fn different_parts_get_different_uuids_but_same_shape() {
        let a = generate_library("PART_A", &synthetic_symbol(), &synthetic_footprint());
        let b = generate_library("PART_B", &synthetic_symbol(), &synthetic_footprint());
        let a_sym_path = &a
            .iter()
            .find(|f| f.path.ends_with("symbol.lp"))
            .unwrap()
            .path;
        let b_sym_path = &b
            .iter()
            .find(|f| f.path.ends_with("symbol.lp"))
            .unwrap()
            .path;
        assert_ne!(a_sym_path, b_sym_path);
    }

    #[test]
    fn signal_roles_use_librepcbs_real_vocabulary() {
        let files = generate_library("TESTPART", &synthetic_symbol(), &synthetic_footprint());
        let component_lp = &files
            .iter()
            .find(|f| f.path.ends_with("component.lp"))
            .unwrap()
            .content;
        assert!(component_lp.contains("(role power)"));
        assert!(component_lp.contains("(role inout)"));
    }

    #[test]
    fn device_pad_count_matches_footprint_pad_count() {
        let files = generate_library("TESTPART", &synthetic_symbol(), &synthetic_footprint());
        let device_lp = &files
            .iter()
            .find(|f| f.path.ends_with("device.lp"))
            .unwrap()
            .content;
        assert_eq!(device_lp.matches("(pad ").count(), 2);
    }
}
