use openparts_mcad::Mounting;
use openparts_pcbcad::{Pad, PadShape, PcbFootprint};

/// Renders a KiCad 6+ `.kicad_mod` footprint file.
pub fn render_footprint(footprint: &PcbFootprint) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "(footprint \"{}\" (version 20221018) (generator openparts)\n",
        footprint.name
    ));
    out.push_str("  (layer \"F.Cu\")\n");
    out.push_str("  (descr \"Generated by OpenParts from Mechanical Geometry\")\n");
    // Every existing (SMD) family keeps today's `smd` attr unchanged;
    // a through-hole part (any pad with drilled `mounting`) gets
    // `through_hole` instead -- this project has no mixed-mounting
    // family yet, so a simple "any THT pad -> through_hole" rule is
    // sufficient without guessing at KiCad's real mixed-footprint
    // convention.
    let is_through_hole = footprint
        .pads
        .iter()
        .any(|p| p.mounting == Mounting::ThroughHole);
    out.push_str(if is_through_hole {
        "  (attr through_hole)\n"
    } else {
        "  (attr smd)\n"
    });
    out.push_str("  (fp_text reference \"REF**\" (at 0 -5.5) (layer \"F.SilkS\")\n");
    out.push_str("    (effects (font (size 1 1) (thickness 0.15))))\n");
    out.push_str(&format!(
        "  (fp_text value \"{}\" (at 0 5.5) (layer \"F.Fab\")\n",
        footprint.name
    ));
    out.push_str("    (effects (font (size 1 1) (thickness 0.15))))\n");

    for pad in &footprint.pads {
        out.push_str(&render_pad(pad));
    }

    out.push(')');
    out.push('\n');
    out
}

/// One `(pad ...)` line. SMD keeps the exact form this crate always
/// used. Through-hole matches a real KiCad reference footprint exactly
/// (`KiCad/kicad-footprints`, `Capacitor_THT.pretty/
/// CP_Radial_D5.0mm_P2.00mm.kicad_mod`): `thru_hole` pad type, a
/// `(drill ...)` field, and `*.Cu`/`*.Mask` layers -- no `F.Paste`,
/// since a through-hole pad has no solder-paste stencil opening.
fn render_pad(pad: &Pad) -> String {
    let shape = match pad.shape {
        PadShape::Rect => "rect",
        PadShape::Circle => "circle",
    };
    match pad.mounting {
        Mounting::Smd => format!(
            "  (pad \"{}\" smd {shape} (at {:.3} {:.3}) (size {:.3} {:.3}) (layers \"F.Cu\" \"F.Paste\" \"F.Mask\"))\n",
            pad.number, pad.position.x, pad.position.y, pad.size.0, pad.size.1
        ),
        Mounting::ThroughHole => {
            let drill = pad.drill.expect("through-hole pad must have a drill diameter");
            format!(
                "  (pad \"{}\" thru_hole {shape} (at {:.3} {:.3}) (size {:.3} {:.3}) (drill {:.3}) (layers \"*.Cu\" \"*.Mask\"))\n",
                pad.number, pad.position.x, pad.position.y, pad.size.0, pad.size.1, drill
            )
        }
    }
}

/// Minimal read-back check used by tests -- see symbol.rs's
/// `parse_symbol_pins` for the same rationale.
#[derive(Debug, PartialEq)]
pub struct ParsedPad {
    pub number: String,
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub height: f64,
    pub mounting: Mounting,
    pub shape: PadShape,
    /// `Some` only for a `thru_hole` pad.
    pub drill: Option<f64>,
}

pub fn parse_footprint_pads(text: &str) -> Vec<ParsedPad> {
    let mut pads = Vec::new();
    for line in text.lines() {
        let trimmed = line.trim_start();
        if !trimmed.starts_with("(pad ") {
            continue;
        }
        let number = extract_quoted(trimmed).expect("pad line must contain a quoted number");

        let mounting = if trimmed.contains(" thru_hole ") {
            Mounting::ThroughHole
        } else {
            Mounting::Smd
        };
        let shape = if trimmed.contains(" circle ") {
            PadShape::Circle
        } else {
            PadShape::Rect
        };

        let at_idx = trimmed
            .find("(at ")
            .expect("pad line must contain (at ...)");
        let after_at = &trimmed[at_idx + 4..];
        let at_close = after_at.find(')').unwrap();
        let mut at_nums = after_at[..at_close].split_whitespace();
        let x: f64 = at_nums.next().unwrap().parse().unwrap();
        let y: f64 = at_nums.next().unwrap().parse().unwrap();

        let size_idx = trimmed
            .find("(size ")
            .expect("pad line must contain (size ...)");
        let after_size = &trimmed[size_idx + 6..];
        let size_close = after_size.find(')').unwrap();
        let mut size_nums = after_size[..size_close].split_whitespace();
        let width: f64 = size_nums.next().unwrap().parse().unwrap();
        let height: f64 = size_nums.next().unwrap().parse().unwrap();

        let drill = trimmed.find("(drill ").map(|drill_idx| {
            let after_drill = &trimmed[drill_idx + 7..];
            let drill_close = after_drill.find(')').unwrap();
            after_drill[..drill_close].trim().parse().unwrap()
        });

        pads.push(ParsedPad {
            number,
            x,
            y,
            width,
            height,
            mounting,
            shape,
            drill,
        });
    }
    pads
}

fn extract_quoted(s: &str) -> Option<String> {
    let start = s.find('"')? + 1;
    let end = start + s[start..].find('"')?;
    Some(s[start..end].to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use openparts_pcbcad::{Pad, PadShape, Point2};

    #[test]
    fn round_trips_pad_number_position_and_size() {
        let footprint = PcbFootprint {
            name: "TEST".into(),
            pads: vec![Pad {
                number: "3".into(),
                position: Point2 { x: -1.5, y: 2.75 },
                size: (0.6, 0.22),
                shape: PadShape::Rect,
                mounting: Mounting::Smd,
                drill: None,
            }],
            graphics: vec![],
            courtyard: None,
        };

        let text = render_footprint(&footprint);
        assert!(text.contains("(attr smd)"));
        let parsed = parse_footprint_pads(&text);
        assert_eq!(parsed.len(), 1);
        assert_eq!(parsed[0].number, "3");
        assert!((parsed[0].x - (-1.5)).abs() < 1e-6);
        assert!((parsed[0].y - 2.75).abs() < 1e-6);
        assert!((parsed[0].width - 0.6).abs() < 1e-6);
        assert!((parsed[0].height - 0.22).abs() < 1e-6);
        assert_eq!(parsed[0].mounting, Mounting::Smd);
        assert_eq!(parsed[0].shape, PadShape::Rect);
        assert_eq!(parsed[0].drill, None);
    }

    #[test]
    fn round_trips_through_hole_pads_with_drill_and_pin1_squared() {
        let footprint = PcbFootprint {
            name: "TEST".into(),
            pads: vec![
                Pad {
                    number: "1".into(),
                    position: Point2 { x: -1.0, y: 0.0 },
                    size: (1.6, 1.6),
                    shape: PadShape::Rect,
                    mounting: Mounting::ThroughHole,
                    drill: Some(0.8),
                },
                Pad {
                    number: "2".into(),
                    position: Point2 { x: 1.0, y: 0.0 },
                    size: (1.6, 1.6),
                    shape: PadShape::Circle,
                    mounting: Mounting::ThroughHole,
                    drill: Some(0.8),
                },
            ],
            graphics: vec![],
            courtyard: None,
        };

        let text = render_footprint(&footprint);
        assert!(text.contains("(attr through_hole)"));
        assert!(
            !text.contains("F.Paste"),
            "through-hole pads must not get a paste layer"
        );
        let parsed = parse_footprint_pads(&text);
        assert_eq!(parsed.len(), 2);
        let pad1 = parsed.iter().find(|p| p.number == "1").unwrap();
        let pad2 = parsed.iter().find(|p| p.number == "2").unwrap();
        assert_eq!(pad1.shape, PadShape::Rect);
        assert_eq!(pad2.shape, PadShape::Circle);
        for pad in &parsed {
            assert_eq!(pad.mounting, Mounting::ThroughHole);
            assert_eq!(pad.drill, Some(0.8));
        }
    }
}
