use openparts_pcbcad::PcbFootprint;

/// Renders a KiCad 6+ `.kicad_mod` footprint file.
pub fn render_footprint(footprint: &PcbFootprint) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "(footprint \"{}\" (version 20221018) (generator openparts)\n",
        footprint.name
    ));
    out.push_str("  (layer \"F.Cu\")\n");
    out.push_str("  (descr \"Generated by OpenParts from Mechanical Geometry\")\n");
    out.push_str("  (attr smd)\n");
    out.push_str("  (fp_text reference \"REF**\" (at 0 -5.5) (layer \"F.SilkS\")\n");
    out.push_str("    (effects (font (size 1 1) (thickness 0.15))))\n");
    out.push_str(&format!(
        "  (fp_text value \"{}\" (at 0 5.5) (layer \"F.Fab\")\n",
        footprint.name
    ));
    out.push_str("    (effects (font (size 1 1) (thickness 0.15))))\n");

    for pad in &footprint.pads {
        out.push_str(&format!(
            "  (pad \"{}\" smd rect (at {:.3} {:.3}) (size {:.3} {:.3}) (layers \"F.Cu\" \"F.Paste\" \"F.Mask\"))\n",
            pad.number, pad.position.x, pad.position.y, pad.size.0, pad.size.1
        ));
    }

    out.push(')');
    out.push('\n');
    out
}

/// Minimal read-back check used by tests -- see symbol.rs's
/// `parse_symbol_pins` for the same rationale.
#[derive(Debug, PartialEq)]
pub struct ParsedPad {
    pub number: String,
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub height: f64,
}

pub fn parse_footprint_pads(text: &str) -> Vec<ParsedPad> {
    let mut pads = Vec::new();
    for line in text.lines() {
        let trimmed = line.trim_start();
        if !trimmed.starts_with("(pad ") {
            continue;
        }
        let number = extract_quoted(trimmed).expect("pad line must contain a quoted number");

        let at_idx = trimmed.find("(at ").expect("pad line must contain (at ...)");
        let after_at = &trimmed[at_idx + 4..];
        let at_close = after_at.find(')').unwrap();
        let mut at_nums = after_at[..at_close].split_whitespace();
        let x: f64 = at_nums.next().unwrap().parse().unwrap();
        let y: f64 = at_nums.next().unwrap().parse().unwrap();

        let size_idx = trimmed.find("(size ").expect("pad line must contain (size ...)");
        let after_size = &trimmed[size_idx + 6..];
        let size_close = after_size.find(')').unwrap();
        let mut size_nums = after_size[..size_close].split_whitespace();
        let width: f64 = size_nums.next().unwrap().parse().unwrap();
        let height: f64 = size_nums.next().unwrap().parse().unwrap();

        pads.push(ParsedPad { number, x, y, width, height });
    }
    pads
}

fn extract_quoted(s: &str) -> Option<String> {
    let start = s.find('"')? + 1;
    let end = start + s[start..].find('"')?;
    Some(s[start..end].to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use openparts_pcbcad::{Pad, PadShape, Point2};

    #[test]
    fn round_trips_pad_number_position_and_size() {
        let footprint = PcbFootprint {
            name: "TEST".into(),
            pads: vec![Pad {
                number: "3".into(),
                position: Point2 { x: -1.5, y: 2.75 },
                size: (0.6, 0.22),
                shape: PadShape::Rect,
            }],
            graphics: vec![],
            courtyard: None,
        };

        let text = render_footprint(&footprint);
        let parsed = parse_footprint_pads(&text);
        assert_eq!(parsed.len(), 1);
        assert_eq!(parsed[0].number, "3");
        assert!((parsed[0].x - (-1.5)).abs() < 1e-6);
        assert!((parsed[0].y - 2.75).abs() < 1e-6);
        assert!((parsed[0].width - 0.6).abs() < 1e-6);
        assert!((parsed[0].height - 0.22).abs() < 1e-6);
    }
}
